### ISSUE TITLE
 Medidata.RWS.NET.Standard 1.0.2 Framework compatibility issue

### ISSUE THREAD

**Issue by nikolayrusev** [mskcc/Medidata.RWS.NET#14] opened 2018-10-24 10:27 UTC
Dear Matt,

What is the framework used for Medidata.RWS.NET.Standard 1.0.2?

I use your previous version and can't use timeouts

Thank you!
Nik

**Comment by mattkoch614** [comment] 2018-10-24 10:41
Duplicate of question on #13. Closing.

**Closed as completed by mattkoch614** 2018-10-24 10:41 UTC

**Comment by nikolayrusev** [comment] 2018-10-24 10:48
I tried to install the Standard package published on 16.8.2018.
Even when using 4.5.2: I receive this error msg:

"Installing 'Medidata.RWS.NET.Standard 1.0.2'.
Successfully installed 'Medidata.RWS.NET.Standard 1.0.2'.
Adding 'Medidata.RWS.NET.Standard 1.0.2' to 02. File-Copy.
Uninstalling 'Medidata.RWS.NET.Standard 1.0.2'.
Successfully uninstalled 'Medidata.RWS.NET.Standard 1.0.2'.
Install failed. Rolling back...
Could not install package 'Medidata.RWS.NET.Standard 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by mattkoch614** [comment] 2018-10-24 13:21
@nikolayrusev Please create an issue on the repository where you are experiencing a problem. 

https://github.com/mskcc/Medidata.RWS.NET.Standard

Your other option is to just use this library instead. That being said, I just created a new Console application targeting the .NET Framework 4.5.1 and installed the Standard version of this library with no issues. What happens if you use a project that targets 4.5.1?
